#! /bin/sh

make || exit 1

echo "============ PART 1 ==============="

echo "EXAMPLE 1"
./aoc 1  < example-1

echo "INPUT"
./aoc 1 < input

echo "============ PART 2 ==============="

echo "EXAMPLE 1"
./aoc 2  < example-1

echo "EXAMPLE 2"
./aoc 2  < example-2

echo "INPUT"
./aoc 2 < input


