#! /bin/sh

make || exit 1

echo "============ PART 1 ==============="

./aoc 1

echo "============ PART 2 ==============="

if [ -s "example-2" ]
then
	echo "EXAMPLE 2"
	./aoc 2  < example-2

	echo "INPUT"
	./aoc 2 < input
fi

