#! /bin/sh

make || exit 1

echo "============ PART 1 ==============="

echo "EXAMPLE 1"
./aoc 1  < example

echo "INPUT"
./aoc 1 < input

echo "============ PART 2 ==============="

echo "EXAMPLE"
./aoc 2  < example

echo "INPUT"
./aoc 2 < input


