#! /bin/sh

make || exit 1

echo "============ PART 1 ==============="

if [ -s "example-1" ]
then
	echo "EXAMPLE 1"
	./aoc 1  < example-1
fi

if [ -s "example-2" ]
then
	echo "EXAMPLE 2"
	./aoc 1  < example-2
fi

if [ -s "input" ]
then
	echo "INPUT"
	./aoc 1 < input
fi

echo "============ PART 2 ==============="

if [ -s "example-3" ]
then
	echo "EXAMPLE 3"
	./aoc 2  < example-3

	echo "EXAMPLE 4"
	./aoc 2  < example-4

	echo "INPUT"
	./aoc 2 < input
fi

