#! /bin/sh

make


echo "============ PART 1 ==============="
echo "EXAMPLE 1"
./aoc 1  < example-1

echo "EXAMPLE 2"
./aoc 1  < example-2


echo "INPUT"

./aoc 1 < input

echo "============ PART 2 ==============="

echo "EXAMPLE 3"

./aoc 2  < example-3

echo "INPUT"

./aoc 2 < input


